### ISSUE TITLE
[BUG] user_following problem

### ISSUE THREAD

**Issue by Laura-Ag** [subzeroid/instagrapi#1676]
Hello,

I have the following piece of code:

int_user_id = API.user_id_from_username(USERNAME)
user_id = str(int_user_id)
print('user id', user_id)
user_followings = API.user_following(user_id, 0)
print("entered")

What I get is: 

Traceback (most recent call last):
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://i.instagram.com/api/v1/friendships/4499923421/following/?max_id=4000&count=200&rank_token=4499923421_da477617-37e3-48e9-ae9c-b39c9cf5bbed&search_surface=follow_list_page&query=&enable_groups=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\laura\Desktop\Workspace\InstaSpector\main.py", line 30, in <module>
    user_followings = API.user_following(user_id, 0)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 616, in user_following
    users = self.user_following_v1(user_id, amount)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 580, in user_following_v1
    users, _ = self.user_following_v1_chunk(str(user_id), amount)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\user.py", line 542, in user_following_v1_chunk
    result = self.private_request(
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 535, in private_request
    raise e
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 520, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\private.py", line 459, in _send_private_request
    raise ClientError(e, response=e.response, **last_json)
instagrapi.exceptions.ClientError: Please wait a few minutes before you try again.

Could anyone help me?

**Comment by PonyOny** [comment]
Same here, started to happen more or less 2 days ago :(

**Comment by Laura-Ag** [comment]
I am facing this problem since January. My issue is still open here [#1050](https://github.com/subzeroid/instagrapi/issues/1050)

**Comment by jarrodnorwell** [comment]
Hey @Laura-Ag, 

Could you send what you have code-wise minus any private information? I'll look into it a bit later. It's possible I missed something in my latest PR regarding `user_following`

**Comment by Laura-Ag** [comment]
Hello @jarrodnorwell thanks for answering!
Here is a piece of my code:

import json

from instagrapi import Client

USERNAME = '##'
PASSWORD = '##'

API = Client()
API.login(USERNAME, PASSWORD)

int_user_id = API.user_id_from_username(USERNAME)
user_id = str(int_user_id)
print('user id', user_id)
user_followings = API.user_following(user_id, 0)
print("entered")

**Comment by jarrodnorwell** [comment]
@Laura-Ag, looks as though it could be because instagrapi's PyPI version is not the one currently on GitHub which has my fixes for the issue you're having, if you run `pip install git+https://github.com/subzeroid/instagrapi` it should install the latest working version

**Comment by Laura-Ag** [comment]
Hello,
thanks for the answer. I did the above, but now I have a different problem. 
I run from instagrapi import Client and I get

**Comment by Laura-Ag** [comment]
Hello @jarrodnorwell, 
any ideas how to fix my problem?

**Comment by jarrodnorwell** [comment]
Hey @Laura-Ag, 

Apologies for not responding sooner, if you do the same command as above my PR to fix the issue about `type` should be fixed, if anything else pops up feel free to let me know!

**Comment by Laura-Ag** [comment]
Hello @jarrodnorwell , 
I installed version 2.0.2 of Instagrapi but it didn't fix the issue. 

Traceback (most recent call last):
  File "c:\Users\laura\Desktop\Workspace\InstaSpector\main.py", line 3, in <module>
    from instagrapi import Client
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\__init__.py", line 7, in <module>
    from instagrapi.mixins.account import AccountMixin
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\mixins\account.py", line 8, in <module>
    from instagrapi.extractors import extract_account, extract_user_short
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\extractors.py", line 6, in <module>
    from .types import (
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\types.py", line 124, in <module>
    class Media(TypesBaseModel):
  File "C:\Users\laura\AppData\Local\Programs\Python\Python39-32\lib\site-packages\instagrapi\types.py", line 125, in Media
    pk: str | int
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by vzardd** [comment]
Did the issue solved for you? @Laura-Ag ? I'm getting the same TypeError issue from the import statement :(

**Comment by Laura-Ag** [comment]
Hello @vzardd,
No, the issue has not been fixed.

**Comment by jarrodnorwell** [comment]
@vzardd @Laura-Ag, after looking into it further it's actually related to my comment on this issue: https://github.com/subzeroid/instagrapi/issues/1694#issuecomment-1855102417, I can make the change but it skews from how the project is meant to work

**Comment by Laura-Ag** [comment]
Hello @Altimis,
Thanks for the answer. 
I updated Python to 3.11 but the issue still remains.

**Comment by Laura-Ag** [comment]
Hey guys!
Any other ideas?

**Comment by diezo** [comment]
there are some features that won't work in instagrapi. try using [this package](https://github.com/diezo/ensta) instead.

```pip install ensta```

```py
from ensta import Host

host = Host(username, password)

for user in host.followings("someone"):
    print(user.username)
```

there are a lot of other features too.

**Comment by jarrodnorwell** [comment]
Just so you're aware @diezo, your module appears to only use the private API which is much more likely to get accounts banned, the good thing about Instagrapi is that it first attempts to use the public API and then falls back to the private if necessary

**Comment by diezo** [comment]
@jarrodnorwell i think you're not aware that you need to be logged in to be able to fetch someone's followers/followings list.

**Comment by Laura-Ag** [comment]
Which are the specs in order for instagrapi to work fine for me? It doesn’t even login to the account.

**Comment by diezo** [comment]
what problem are you facing with instagrapi?

**Comment by Laura-Ag** [comment]
Python 3.11 finally worked.
Thank you!
